using EntityFrameworkExample.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;

namespace EntityFrameworkExample.Data.Configurations
{
    public class ExampleEntityConfiguration : EntityTypeConfiguration<ExampleEntity>
    {
        public ExampleEntityConfiguration()
        {
            //tell the database you want the id to be autogenerated
            HasKey(ee => ee.Id);

            //our entity can have many exampleChilds tied to it
            HasMany(ee => ee.ExampleChildEntities)
                //the children MUST have a parent entity if they are saved to the db
                .WithRequired(ece => ece.ParentEntity)

                //the foriegn key on the child is named ParentEntityId
                .HasForeignKey(ece => ece.ParentEntityId);
        }
    }
}