using EntityFrameworkExample.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;

namespace EntityFrameworkExample.Data.Configurations
{
    public class ExampleChildEntityConfiguration : EntityTypeConfiguration<ExampleChildEntity>
    {
        public ExampleChildEntityConfiguration()
        {
            //tell the database you want the id to be autogenerated
            HasKey(ece => ece.Id);

            //this entity has a required parent
            HasRequired(ece => ece.ParentEntity)
                //the parent has many children
                .WithMany()
                //the child as the foreign key named ParentEntityId
                .HasForeignKey(ece => ece.ParentEntityId);
        }
    }
}